<?php

/**
 * Implements hook_flush_caches().
 */
function fr_services_flush_caches() {
  return array('cache_fr_services');
}

/**
 * Delivery callback for services. Ensure we've got proper JSON response.
 *
 * @param $page_callback_result
 */
function fr_services_delivery_callback($page_callback_result) {
  if ($page_callback_result == MENU_NOT_FOUND) {
    drupal_add_http_header('Status', '404 Not Found');
    return;
  }

  if ($page_callback_result == MENU_ACCESS_DENIED) {
    drupal_add_http_header('Status', '403 Forbidden');
    return;
  }

  drupal_add_http_header('Content-Type', 'application/json');
  drupal_add_http_header('Cache-Control', 'no-cache, must-revalidate, post-check=0, pre-check=0');
  print drupal_json_encode($page_callback_result);
}
