<?php
/**
 * @file
 * Code for the FR Content Wallboard feature.
 */

include_once 'fr_content_wallboard.features.inc';

/**
 * Implements hook_menu_local_tasks_alter().
 */
function fr_content_wallboard_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  switch ($root_path) {
    case 'admin/wallboards':
      $item = menu_get_item('node/add/wallboard');
      if ($item['access']) {
        $item['title'] = t('Add new wallboard');
        $data['actions']['output'][] = array(
          '#theme' => 'menu_local_action',
          '#link' => $item,
        );
      }
      break;
  }
}

/**
 * Implements hook_preprocess_page().
 */
function fr_content_wallboard_preprocess_page(&$vars) {
  if (isset($vars['node'])) {
    $node = $vars['node'];
  }

  // Add slide dashboard entity in wallboard view.
  if (isset($node) && $node->type == "wallboard") {
    $settings = array();

    // Get slide duration value
    $item = field_get_items('node', $node, 'field_slide_duration', $node->language);
    $settings['duration'] = $item['0']['value'];

    // Get slide transition speed value
    $item = field_get_items('node', $node, 'field_slide_transition_speed', $node->language);
    $settings['transitionSpeed'] = $item['0']['value'];

    //Get slide effect
    $item = field_get_items('node', $node, 'field_slide_effect', $node->language);
    $settings['effect'] = $item['0']['value'];

    // Pass $settings array as js setting
    drupal_add_js(array('wallboardSlide' => array('slideSettings' => $settings)), 'setting');
    drupal_add_js(drupal_get_path('module', 'fr_content_wallboard').'/js/wallboard_transitions.js');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function fr_content_wallboard_preprocess_node(&$vars) {
  // Display dashboard entity ID as rendered panelizer item
  if ($vars['type'] == 'wallboard') {
    ctools_include('plugins');
    $plugin = ctools_get_plugins('page_manager', 'tasks', 'node_view');
    foreach ($vars['field_dashboards'] as $key => $value) {
      unset($vars['content']['field_dashboards'][$key]['#markup']);
      $vars['content']['field_dashboards'][$key] = page_manager_node_view_page($value['entity']);
    }
  }
}
