<?php

/**
 * Implements hook_enable().
 */
function fr_dev_enable() {
  // Disable aggregation of CSS and JS.
  variable_set('preprocess_css', 0);
  variable_set('preprocess_js', 0);

  // Turn on displaying of error messages.
  variable_set('error_level', 2);

  // Disable modules
  $module_list = array(
    'update',
  );
  module_disable($module_list, TRUE);
}

/**
 * Implements hook_disable().
 */
function fr_dev_disable() {
  // Enable aggregation of CSS and JS.
  variable_set('preprocess_css', 1);
  variable_set('preprocess_js', 1);

  // Turn logging off (None).
  variable_set('error_level', 0);
}
